import { z } from 'zod';
import {
  createSelectSchema,
  createInsertSchema,
  createUpdateSchema,
} from 'drizzle-zod';
import { activities } from '@corpcal/database/schema';
import { CALENDAR_VISIBILITY } from '../constants/activity-enums';

/**
 * Activity Zod schemas automatically generated from Drizzle schema
 * These schemas ensure validation matches the database schema exactly
 *
 * Generated from: packages/database/src/schema/activity.ts
 */

/**
 * Schema for selecting activities from the database
 * Matches the shape of data returned from database queries
 */
export const activitySchema = createSelectSchema(activities);

/**
 * Schema for creating a new activity (insert)
 * Automatically excludes generated columns (id, audit fields, etc.)
 */
export const createActivitySchema = createInsertSchema(activities);

/**
 * Schema for updating an activity (partial update)
 * Automatically excludes generated columns and makes all fields optional
 */
export const updateActivitySchema = createUpdateSchema(activities);

/**
 * Schema for creating a new activity via HTTP request
 * Dates are accepted as ISO date strings (YYYY-MM-DD) and time strings (HH:mm)
 * This is the schema that should be used for API request validation
 */
export const createActivityRequestSchema = createInsertSchema(activities, {
  // Required fields that must be explicitly included to ensure TypeScript type checking
  // These fields are .notNull() in the database schema but drizzle-zod may not enforce them properly
  dateStatusId: z.number().int(),
  timeStatusId: z.number().int(),
  pitchStatusId: z.number().int(),
  activityStatusId: z.number().int(),
  ownerId: z.number().int(),
  calendarVisibility: z.enum(CALENDAR_VISIBILITY),
  // Transform empty strings to null for nullable UUID fields
  // This handles form inputs where empty fields send "" instead of null
  newsReleaseId: z.preprocess(
    (val) => (val === '' ? null : val),
    z.string().uuid().nullable().optional()
  ),
  leadOrgId: z.preprocess(
    (val) => (val === '' ? null : val),
    z.string().uuid().nullable().optional()
  ),
  eventLeadOrgId: z.preprocess(
    (val) => (val === '' ? null : val),
    z.string().uuid().nullable().optional()
  ),
  newsReleaseOriginId: z.preprocess(
    (val) => (val === '' ? null : val),
    z.string().uuid().nullable().optional()
  ),
  // Transform venueAddress: handle both string (legacy) and object formats
  // If string is provided, convert to null (can't reliably parse free-form string)
  // If object is provided, validate it has the correct structure
  venueAddress: z.preprocess(
    (val) => {
      // If it's already null or undefined, return as-is
      if (val === null || val === undefined) return null;
      // If it's a string, return null (legacy format - can't parse reliably)
      if (typeof val === 'string') return null;
      // If it's an object, return it (will be validated by the schema)
      if (typeof val === 'object') return val;
      // For any other type, return null
      return null;
    },
    z
      .object({
        street: z.string(),
        city: z.string(),
        provinceOrState: z.string(),
        country: z.string(),
      })
      .nullable()
      .optional()
  ),
})
  .omit({
    id: true, // Exclude id - it's auto-generated by the database
    displayId: true, // Exclude computed field
    rowVersion: true, // Exclude row version - set by backend
    createdBy: true, // Exclude audit fields - set by backend
    lastUpdatedBy: true,
    createdDateTime: true,
    lastUpdatedDateTime: true,
  })
  .extend({
    // Junction table data - arrays of IDs to create relationships
    categoryIds: z.array(z.number().int()).optional(),
    tagIds: z.array(z.string().uuid()).optional(),
    jointOrgIds: z.array(z.string().uuid()).optional(),
    relatedActivityIds: z.array(z.number().int()).optional(),
    commsMaterialIds: z.array(z.number().int()).optional(),
    translationLanguageIds: z.array(z.number().int()).optional(),
    jointEventOrgIds: z.array(z.string().uuid()).optional(),
    representativeIds: z.array(z.number().int()).optional(), // For activityRepresentatives
    sharedWithOrgIds: z.array(z.string().uuid()).optional(),
    canEditUserIds: z.array(z.number().int()).optional(),
    canViewUserIds: z.array(z.number().int()).optional(),
    additionalOwnerIds: z.array(z.number().int()).optional(),
  });

/**
 * Schema for updating an activity via HTTP request
 * Dates are accepted as ISO date strings (YYYY-MM-DD) and time strings (HH:mm)
 * ID is not included in the request body (it comes from the URL parameter)
 * This is the schema that should be used for API request validation
 *
 * Note: XOR validation (leadOrgId/leadOrgName, etc.) is handled by database CHECK constraints
 * in the Drizzle schema, so we don't need to duplicate it here in Zod.
 */
export const updateActivityRequestSchema = updateActivitySchema.partial();

/**
 * Schema for filtering activities (query parameters)
 * Uses z.coerce for query parameters which come as strings from HTTP
 */
export const filterActivitiesSchema = z.object({
  title: z.string().optional(),
  startDateFrom: z.iso.date().optional(),
  startDateTo: z.iso.date().optional(),
  endDateFrom: z.iso.date().optional(),
  endDateTo: z.iso.date().optional(),
  activityStatusId: z.coerce.number().int().optional(),
  ministryOwnerId: z.uuid().optional(),
  city: z.string().optional(),
  isActive: z.coerce.boolean().optional(),
  isIssue: z.coerce.boolean().optional(),
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().min(1).max(100).default(20),
});

/**
 * TypeScript types inferred from Zod schemas
 *
 * These types are automatically inferred from the Zod schemas generated by drizzle-zod.
 * They should match the types from @corpcal/database/types, but are validated at runtime
 * through the Zod schemas.
 *
 * Note: Activity type is not exported here to avoid conflict with @corpcal/database/types.
 * Use Activity from @corpcal/database/types or @corpcal/shared for the database type.
 */
// Activity type is available from @corpcal/database/types - not exported here to avoid conflicts
export type CreateActivity = z.infer<typeof createActivitySchema>;
export type UpdateActivity = z.infer<typeof updateActivitySchema>;
export type CreateActivityRequest = z.infer<typeof createActivityRequestSchema>;
export type UpdateActivityRequest = z.infer<typeof updateActivityRequestSchema>;
export type FilterActivities = z.infer<typeof filterActivitiesSchema>;
