apiVersion: v1
kind: ConfigMap
metadata:
  name: corpcal-service-config
data:
  AUTH_COOKIE_DOMAIN: calendar-ui-dc4c90-dev.apps.emerald.devops.gov.bc.ca
  POST_LOGIN_REDIRECT_URL: https://calendar-ui-dc4c90-dev.apps.emerald.devops.gov.bc.ca
  CORS_ALLOWED_ORIGINS: https://calendar-ui-dc4c90-dev.apps.emerald.devops.gov.bc.ca,http://localhost:3000,http://localhost:4173,http://localhost:8080
