apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: corpcal-postgres-pvc
  labels:
    app.kubernetes.io/name: corpcal
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: corporate-calendar
    app.kubernetes.io/version: '16'
    app.kubernetes.io/managed-by: github-actions
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
