apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: corpcal-postgres
  labels:
    app: corpcal-postgres
    app.kubernetes.io/name: corpcal
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: corporate-calendar
    app.kubernetes.io/version: '16'
    app.kubernetes.io/managed-by: github-actions
spec:
  serviceName: corpcal-postgres
  replicas: 1
  selector:
    matchLabels:
      app: corpcal-postgres

  template:
    metadata:
      labels:
        app: corpcal-postgres
    spec:
      # OpenShift restricted SCC safe
      securityContext: {}
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: corpcal-postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: corpcal-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: corpcal-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ['pg_isready', '-U', 'postgres']
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ['pg_isready', '-U', 'postgres']
            initialDelaySeconds: 30
            periodSeconds: 20

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: corpcal-postgres-pvc
