apiVersion: v1
kind: Secret
metadata:
  name: corpcal-postgres-secret
  labels:
    app.kubernetes.io/name: corpcal
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: corporate-calendar
    app.kubernetes.io/version: '16'
    app.kubernetes.io/managed-by: github-actions
type: Opaque
stringData:
  POSTGRES_DB: calendar
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: calendarpwd
