-- DEPRECATED: This file previously contained SQL to fix all auto-increment
-- sequences to be in sync with existing data.
--
-- To apply the sequence fixes, use the canonical migration script instead:
--   packages/database/migrations/003_fix_sequences.sql
--
-- This file is intentionally left without executable SQL to avoid having
-- duplicate scripts that can drift out of sync. It is kept only for
-- backward compatibility with any existing references to `fix-sequence.sql`.
