apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: calendar-service
  labels:
    app.kubernetes.io/name: calendar
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: corporate-calendar
    app.kubernetes.io/managed-by: kubectl
