apiVersion: v1
kind: Secret
metadata:
  name: corpcal-service-secret
  labels:
    app.kubernetes.io/name: corpcal
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: corporate-calendar
    app.kubernetes.io/version: ${APP_VERSION}
    app.kubernetes.io/managed-by: github-actions
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:calendarpwd@corpcal-postgres:5432/calendar
  JWT_SECRET: ${JWT_SECRET}
  AZURE_TENANT_ID: ${AZURE_TENANT_ID}
  AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
  AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
  AZURE_REDIRECT_URI: ${AZURE_REDIRECT_URI}
