apiVersion: v1
kind: Secret
metadata:
  name: calendar-service-secrets
  labels:
    app.kubernetes.io/name: calendar
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: corporate-calendar
    app.kubernetes.io/instance: dev
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:calendarpwd@calendar-postgres:5432/calendar
