// Generated by scripts/build-corpcal-tokens.mjs. Do not edit by hand.
// Concatenates bcds-primitives.css + corpcal-tokens.css for embedded print/PDF.
export const CORPCAL_SEMANTIC_TOKEN_CSS = `/*
 * Canonical BC / BCDS color primitives for the monorepo.
 * Import before corpcal-tokens.css (and embedded print CSS is built from this + corpcal).
 * https://www2.gov.bc.ca/gov/content/digital/design-system/foundations/design-tokens/glossary
 */
:root {
  /* BC Government Brand Colors */
  --bc-blue: #013366;
  --bc-blue-light: #1a4b82;
  --bc-gold: #fcba19;
  --bc-gold-dark: #e8a317;

  /* BCSDS color primitives (simplified from BC Design System tokens) */
  --bcsds-gold-10: #fff8e9;
  --bcsds-gold-15: #fef1d8;
  --bcsds-gold-20: #feebc2;
  --bcsds-gold-30: #fddf9d;
  --bcsds-gold-40: #fdd47b;
  --bcsds-gold-50: #fcc85d;
  --bcsds-gold-60: #f8ba47;
  --bcsds-gold-65: #e3a82b;
  --bcsds-gold-70: #ce9737;
  --bcsds-gold-80: #a5792b;
  --bcsds-gold-90: #7e5d21;
  --bcsds-gold-100: #584215;
  --bcsds-bc-blue-5: #f7f9fc;
  --bcsds-bc-blue-10: #f1f8fe;
  --bcsds-bc-blue-20: #d8eafd;
  --bcsds-bc-blue-30: #c1ddfc;
  --bcsds-bc-blue-40: #a8d0fb;
  --bcsds-bc-blue-50: #91c4fa;
  --bcsds-bc-blue-60: #7ab8f9;
  --bcsds-bc-blue-70: #5595d9;
  --bcsds-bc-blue-80: #3470b1;
  --bcsds-bc-blue-90: #1e5189;
  --bcsds-bc-blue-95: #234075;
  --bcsds-bc-blue-99: #013366;
  --bcsds-bc-blue-100: #053662;
  --bcsds-bc-blue-110: #083155;
  --bcsds-link-blue-60: #2e5dd7;
  --bcsds-aqua-blue-70: #2378c7;
  --bcsds-aqua-blue-90: #255a90;
  --bcsds-warm-grey-10: #faf9f8;
  --bcsds-warm-grey-20: #f3f2f1;
  --bcsds-warm-grey-30: #eceae8;
  --bcsds-warm-grey-40: #e0dedc;
  --bcsds-warm-grey-50: #d1cfcd;
  --bcsds-warm-grey-60: #c6c5c3;
  --bcsds-warm-grey-70: #9f9d9c;
  --bcsds-warm-grey-75: #898785;
  --bcsds-warm-grey-80: #605e5c;
  --bcsds-warm-grey-85: #474543;
  --bcsds-warm-grey-90: #3d3c3b;
  --bcsds-warm-grey-100: #353433;
  --bcsds-warm-grey-110: #252423;
  --bcsds-neutral-grey-50: #d8d8d8;
  --bcsds-neutral-grey-105: #2d2d2d;
  --bcsds-red-15: #f4e1e2;
  --bcsds-red-60: #ce3e39;
  --bcsds-red-80: #a2312d;
  --bcsds-red-90: #902b28;
  --bcsds-green-5: #f6fff8;
  --bcsds-green-60: #42814a;
  --bcsds-green-80: #35673b;
  --bcsds-green-90: #2e5a34;
  --bcsds-white-00: #ffffff;
  --bcsds-white-opacity-00-15: #ffffff15;
  --bcsds-white-opacity-00-05: #ffffff05;
  --bcsds-white-opacity-00-45: #ffffff45;
  --bcsds-white-opacity-00-10: #ffffff10;
  --bcsds-white-opacity-00-20: #ffffff20;
  --bcsds-black-100: #000000;
  --bcsds-black-opacity-100-00: #00000000;
  --bcsds-black-opacity-100-45: #00000045;
  --bcsds-black-opacity-100-15: #00000015;
  --bcsds-black-opacity-100-05: #00000005;
  --bcsds-black-opacity-100-10: #00000010;
}

:root {
  --corpcal-surface: var(--background, oklch(1 0 0));
  --corpcal-surface-muted: var(--muted, oklch(0.97 0 0));
  --corpcal-surface-subtle: color-mix(
    in oklch,
    var(--corpcal-surface-muted) 60%,
    var(--corpcal-surface)
  );
  --corpcal-text: var(--foreground, oklch(0.145 0 0));
  --corpcal-text-muted: var(--muted-foreground, oklch(0.556 0 0));
  --corpcal-text-subtle: color-mix(
    in oklch,
    var(--corpcal-text-muted) 78%,
    var(--corpcal-surface)
  );
  --corpcal-border: var(--border, oklch(0.922 0 0));
  --corpcal-radius: var(--radius, 0.625rem);
  --corpcal-radius-md: calc(var(--corpcal-radius) - 2px);
  --corpcal-radius-sm: calc(var(--corpcal-radius) - 4px);

  --corpcal-table-surface: var(--corpcal-surface);
  --corpcal-table-border: var(--corpcal-border);
  --corpcal-table-radius: var(--corpcal-radius-md);
  --corpcal-table-header-bg: color-mix(
    in oklch,
    var(--corpcal-surface-muted) 95%,
    var(--corpcal-surface)
  );
  --corpcal-table-header-fg: var(--corpcal-text);
  --corpcal-table-row-bg: var(--corpcal-surface);
  --corpcal-table-row-alt-bg: var(--corpcal-surface-subtle);
  --corpcal-table-row-hover-bg: color-mix(
    in oklch,
    var(--accent, oklch(0.97 0 0)) 30%,
    transparent
  );
  --corpcal-table-cell-fg: var(--corpcal-text);
  --corpcal-table-cell-muted-fg: var(--corpcal-text-muted);
  --corpcal-table-cell-subtle-fg: var(--corpcal-text-subtle);

  /* Inline / text links — matches calendar-ui \`--link\` / \`--primary\` when present; solid fallback for standalone PDF */
  --corpcal-link: var(--link, var(--primary, #0f6cbd));

  /* Issue / confidential labels (~Tailwind red-600); shared UI + report print */
  --corpcal-text-alert: var(--bcsds-red-60);

  /* Print/report pills & accents (BCDS primitives in bcds-primitives.css; embedded with them for PDF) */
  --corpcal-print-accent-red: var(--bcsds-red-90);
  --corpcal-print-accent-red-soft: var(--bcsds-red-15);
  --corpcal-print-accent-blue: var(--bcsds-bc-blue-90);
  --corpcal-print-accent-blue-soft: var(--bcsds-bc-blue-20);
  --corpcal-print-accent-amber: var(--bcsds-gold-80);
  --corpcal-print-accent-amber-soft: var(--bcsds-gold-15);
}
`;
