apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calendar-service/configmap.yaml
  - calendar-service/imagestream.yaml
  - calendar-service/deployment.yaml
  - calendar-service/service.yaml
  - calendar-service/route.yaml
  - calendar-ui/configmap.yaml
  - calendar-ui/imagestream.yaml
  - calendar-ui/deployment.yaml
  - calendar-ui/service.yaml
  - calendar-ui/route.yaml
  - database/postgres-pvc.yaml
  - database/postgres-statefulset.yaml
  - database/postgres-service.yaml
# secrets are not included in the resources list to avoid exposing sensitive information in the kustomization.yaml file
# apply secrets separately using kubectl apply -f calendar-service/secret.yaml, kubectl apply -f calendar-ui/secret.yaml, and kubectl apply -f database/postgres-secret.yaml
