apiVersion: v1
kind: ConfigMap
metadata:
  name: corpcal-ui-config
  labels:
    app.kubernetes.io/name: corpcal
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: corporate-calendar
    app.kubernetes.io/version: ${APP_VERSION}
    app.kubernetes.io/managed-by: github-actions
data:
  NODE_ENV: development
  VITE_API_BASE_URL: /api
  API_PROXY_UPSTREAM: http://corpcal-service:3001
