apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: corpcal-ui-route
  labels:
    app.kubernetes.io/name: corpcal
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: corporate-calendar
    app.kubernetes.io/version: ${APP_VERSION}
    app.kubernetes.io/managed-by: github-actions
spec:
  to:
    kind: Service
    name: corpcal-ui
  port:
    targetPort: http
  tls:
    termination: edge
