apiVersion: v1
kind: Secret
metadata:
  name: corpcal-ui-secret
  labels:
    app.kubernetes.io/name: corpcal
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: corporate-calendar
    app.kubernetes.io/version: ${APP_VERSION}
    app.kubernetes.io/managed-by: github-actions
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:calendarpwd@corpcal-postgres:5432/calendar
