apiVersion: v1
kind: Secret
metadata:
  name: calendar-postgres-secret
  labels:
    app.kubernetes.io/name: calendar
    app.kubernetes.io/component: postgres
    app.kubernetes.io/part-of: corporate-calendar
    app.kubernetes.io/instance: dev
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  POSTGRES_DB: calendar
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: calendarpwd
