apiVersion: v1
kind: Service
metadata:
  name: calendar-postgres
  labels:
    app.kubernetes.io/name: calendar
    app.kubernetes.io/component: postgres
    app.kubernetes.io/part-of: corporate-calendar
    app.kubernetes.io/instance: dev
    app.kubernetes.io/managed-by: kubectl
spec:
  clusterIP: None # headless service
  selector:
    app: calendar-postgres
  ports:
    - port: 5432
      targetPort: 5432
