import type { ActivityResponse } from '../../schemas/activity-response.schema';

export const BASE_ACTIVITY: ActivityResponse = {
  id: 101,
  displayId: 'ACT-101',
  isIssue: true,
  isConfidential: false,
  title: 'Minister announces housing investment',
  summary: 'Summary text',
  significance: null,
  leadOrgId: null,
  leadOrgName: null,
  isAllDay: false,
  startDate: '2026-04-28T00:00:00.000Z',
  endDate: null,
  dateStatusId: undefined,
  startTime: '10:00',
  endTime: null,
  timeStatusId: undefined,
  venueStatusId: null,
  schedulingNotes: null,
  strategy: null,
  newsReleaseOriginId: null,
  newsReleaseId: null,
  newsReleaseDistributionId: null,
  executiveSummary: 'Executive summary',
  lookAheadStatus: 'new',
  lookAheadSection: 'events',
  notes: null,
  pitchDate: null,
  pitchRequiredStatusId: null,
  translationsRequiredStatusId: null,
  premierRequestedId: null,
  visibility: 'global',
  leadTeamId: 1,
  leadMinistryId: 1,
  activityStatusId: 1,
  createdBy: 1,
  lastUpdatedBy: 1,
  createdDateTime: '2026-04-20T00:00:00.000Z',
  lastUpdatedDateTime: '2026-04-26T17:05:00.000Z',
  category: ['Announcement'],
  tags: [],
  commsMaterials: [],
  translationsRequired: [],
  representativesAttending: [],
  sharedWith: [],
  commsContacts: [],
  leadOrg: 'Ministry of Housing',
  eventPlannerDetails: [],
  eventPlanners: [],
  eventPlannerLeadIds: [],
  dateStatus: 'confirmed',
  timeStatus: 'confirmed',
  venueStatus: 'confirmed',
  activityStatus: 'active',
  newsReleaseOrigin: null,
  newsReleaseDistribution: null,
  premierRequested: null,
  pitchRequiredStatus: null,
  translationsRequiredStatus: null,
  leadMinistry: 'Housing',
  leadMinistryAbbreviation: 'HOUS',
  leadTeamDisplayName: null,
  venueAddress: null,
  reportSettings: [],
  flags: [],
};
